apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
    name: pausemane-stream-overlay
    labels:
        app: pausemane-stream-overlay

spec:
    backendType: systemManager
    template:
        metadata:
            namespace: '{{ .Release.Namespace }}'
            labels:
                app: pausemane-stream-overlay

    data:
        {{- range $envName, $ssmPath := .Values.env }}
        - name: {{ $envName }}
          key: {{ $ssmPath }}
        {{- end }}
