apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
    name: pausemane-stream-overlay
    labels:
        app: pausemane-stream-overlay

spec:
    backendType: systemManager
    template:
        metadata:
            namespace: '{{ .Release.Namespace }}'
            labels:
                app: pausemane-stream-overlay

    data:
        - key: /pausemane-stream-overlay/postgresql/database
          name: POSTGRESQL_DATABASE

        - key: /pausemane-stream-overlay/postgresql/host
          name: POSTGRESQL_HOST

        - key: /pausemane-stream-overlay/postgresql/port
          name: POSTGRESQL_PORT

        - key: /pausemane-stream-overlay/postgresql/user
          name: POSTGRESQL_USER

        - key: /pausemane-stream-overlay/postgresql/password
          name: POSTGRESQL_PASSWORD

        - key: /pausemane-stream-overlay/websocket/host
          name: WEBSOCKET_HOST

        # - key: /pausemane-stream-overlay/websocket/port
        #   name: WEBSOCKET_PORT

        - key: /pausemane-stream-overlay/websocket/path
          name: WEBSOCKET_PATH

        # - key: /pausemane-stream-overlay/websocket/trust_proxy
        #   name: WEBSOCKET_TRUST

        - key: /pausemane-stream-overlay/health/host
          name: HEALTH_HOST

        # - key: /pausemane-stream-overlay/health/port
        #   name: HEALTH_PORT

        # - key: /pausemane-stream-overlay/health/path
        #   name: HEALTH_PATH

        # - key: /pausemane-stream-overlay/health/trust_proxy
        #   name: HEALTH_TRUST

        # - key: /pausemane-stream-overlay/health/uptime
        #   name: HEALTH_UPTIME

        - key: /pausemane-stream-overlay/metrics/host
          name: METRICS_HOST

        # - key: /pausemane-stream-overlay/metrics/port
        #   name: METRICS_PORT

        # - key: /pausemane-stream-overlay/metrics/path
        #   name: METRICS_PATH

        # - key: /pausemane-stream-overlay/metrics/trust_proxy
        #   name: METRICS_TRUST

        - key: /pausemane-stream-overlay/twitch/user
          name: TWITCH_USER

        - key: /pausemane-stream-overlay/twitch/token
          name: TWITCH_TOKEN

        - key: /pausemane-stream-overlay/twitch/room
          name: TWITCH_ROOM
