apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: pausemane-stream-overlay
    namespace: monitoring
    labels:
        release: kube-prometheus

spec:
    selector:
        matchLabels:
            app: pausemane-stream-overlay

    namespaceSelector:
        matchNames:
            - '{{ .Release.Namespace }}'

    endpoints:
        - port: metrics
          interval: 30s
