name: app
on:
    push:
        branches:
            - main
        paths:
            # Package
            - packages/app/**/*
            # Workflow
            - .github/workflows/app.yaml
    pull_request:
        paths:
            # Package
            - packages/app/**/*
            # Workflow
            - .github/workflows/app.yaml
jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2

            - name: Use Node.js v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Restore Dependency Cache
              uses: actions/cache@v2
              id: cache
              with:
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
                  path: |
                      node_modules
                      **/node_modules

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn --frozen-lockfile

            - name: Prettier
              working-directory: packages/app
              run: yarn format

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2

            - name: Use Node.js v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Restore Dependency Cache
              uses: actions/cache@v2
              id: cache
              with:
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
                  path: |
                      node_modules
                      **/node_modules

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn --frozen-lockfile

            - name: Build
              working-directory: packages/app
              run: yarn build
              env:
                  GENERATE_SOURCEMAP: false
                  SKIP_PREFLIGHT_CHECK: true

    deploy:
        runs-on: ubuntu-latest

        needs: [formatting, build]
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2

            - name: Use Node.js v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Restore Dependency Cache
              uses: actions/cache@v2
              id: cache
              with:
                  key: ${{ runner.os }}-${{ hashFiles('app/yarn.lock') }}
                  path: app/node_modules

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn --frozen-lockfile

            - name: Build
              working-directory: packages/app
              run: yarn build
              env:
                  GENERATE_SOURCEMAP: false
                  SKIP_PREFLIGHT_CHECK: true

            - name: Upload to S3
              uses: jakejarvis/s3-sync-action@v0.5.1
              env:
                  SOURCE_DIR: './packages/app/build'
                  AWS_REGION: 'us-west-2'
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Invalidate Cloudflare Cache
              uses: jakejarvis/cloudflare-purge-action@v0.3.0
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
